// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwwwtimubaxeyusphjjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3d3d0aW11YmF4ZXl1c3Boamp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODYyODYsImV4cCI6MjA2MDQ2MjI4Nn0.FcVQiAUaqY1tClzBAq4jiFKdmgKE1hToNfhYJ1Q72eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);